#default
spring:
  application:
    name: command-api-app
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.targetcoders.springbootcodingstyle: DEBUG

---
#product
spring.config.activate.on-profile: product
logging:
  level:
    org.hibernate.SQL: INFO
    com.targetcoders.springbootcodingstyle: INFO
